kind: pipeline
name: default

services:
- name: docker
  image: docker:stable-dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

steps:
- name: build
  image: rootfs-build:latest
  pull: always
  environment:
    BUILDKIT_HOST: tcp://buildkitd.ci.svc:1234
  commands:
    - make
    - make images
    - make rootfs-base
    - make initramfs-base
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
